name: playon
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.19
  iconsax: ^0.0.8
  provider: ^6.0.5
  dio: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/IMG_COM_20230306_1042_44_6443.jpg
    - assets/IMG_COM_20230306_1042_44_65115.jpg
    - assets/IMG_COM_20230306_1044_02_69011.jpg
    - assets/IMG_COM_20230306_1046_59_5275.jpg
    - assets/IMG_COM_20230306_1046_59_56113.jpg
    
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Light.ttf
          weight: 300
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/Rubik-Black.ttf
          weight: 900
